version: '3'
services:
  postgresql:
    image: postgres
    container_name: postgres-lesson
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=Julian
      - POSTGRES_PASSWORD=yulian20
      - POSTGRES_DATABASE=postgres
    command: postgres
    restart: always

  redis:
    image: redis:alpine3.14
    container_name: redis-lesson
    ports:
      - '6379:6379'
